export const QUESTIONS = [
  {
    id: "q001",
    dimension: "Motivation",
    type: "Empathique",
    text: "Je recherche des contacts chaleureux pour me sentir en phase avec mon entourage.",
  },
  {
    id: "q002",
    dimension: "Motivation",
    type: "Empathique",
    text: "Être reconnu pour ma gentillesse me pousse à donner le meilleur de moi-même.",
  },
  {
    id: "q003",
    dimension: "Motivation",
    type: "Empathique",
    text: "La convivialité d'une équipe est plus importante pour moi que la compétition.",
  },
  {
    id: "q004",
    dimension: "Motivation",
    type: "Empathique",
    text: "Je me sens motivé quand on me remercie sincèrement pour mon soutien.",
  },
  {
    id: "q005",
    dimension: "Motivation",
    type: "Empathique",
    text: "Je suis prêt à aider sans réserve lorsque je me sens apprécié.",
  },
  {
    id: "q006",
    dimension: "Motivation",
    type: "Empathique",
    text: "Je choisis rarement un projet dépourvu d'humanité, même s'il est rentable.",
  },

  {
    id: "q007",
    dimension: "Force",
    type: "Empathique",
    text: "J'arrive à comprendre l’humeur des autres sans qu’ils ne parlent.",
  },
  {
    id: "q008",
    dimension: "Force",
    type: "Empathique",
    text: "Je crée naturellement une ambiance détendue et accueillante.",
  },
  {
    id: "q009",
    dimension: "Force",
    type: "Empathique",
    text: "Je fais passer les besoins émotionnels de chacun avant les procédures.",
  },
  {
    id: "q010",
    dimension: "Force",
    type: "Empathique",
    text: "On me sollicite souvent pour calmer les tensions.",
  },
  {
    id: "q011",
    dimension: "Force",
    type: "Empathique",
    text: "Je perçois rapidement quand quelqu'un ne se sent pas inclus.",
  },
  {
    id: "q012",
    dimension: "Force",
    type: "Empathique",
    text: "Je sais exprimer de l’empathie même sous pression.",
  },

  {
    id: "q013",
    dimension: "Stress",
    type: "Empathique",
    text: "Une critique peut me troubler pendant des heures.",
  },
  {
    id: "q014",
    dimension: "Stress",
    type: "Empathique",
    text: "Je minimise mes besoins pour éviter de déranger.",
  },
  {
    id: "q015",
    dimension: "Stress",
    type: "Empathique",
    text: "Quand je me sens exclu, j'ai du mal à me concentrer.",
  },
  {
    id: "q016",
    dimension: "Stress",
    type: "Empathique",
    text: "Je peux accepter des tâches supplémentaires pour maintenir la paix.",
  },
  {
    id: "q017",
    dimension: "Stress",
    type: "Empathique",
    text: "Je prends immédiatement la responsabilité lorsqu'un conflit surgit.",
  },
  {
    id: "q018",
    dimension: "Stress",
    type: "Empathique",
    text: "Je me sens coupable si quelqu'un est contrarié à cause de moi.",
  },

  {
    id: "q019",
    dimension: "Motivation",
    type: "Travaillomane",
    text: "Être reconnu pour la qualité de mon travail me stimule.",
  },
  {
    id: "q020",
    dimension: "Motivation",
    type: "Travaillomane",
    text: "Je suis motivé lorsqu'un projet a des objectifs mesurables.",
  },
  {
    id: "q021",
    dimension: "Motivation",
    type: "Travaillomane",
    text: "Un planning précis me donne de l'énergie.",
  },
  {
    id: "q022",
    dimension: "Motivation",
    type: "Travaillomane",
    text: "J'aime que mon expertise technique soit valorisée.",
  },
  {
    id: "q023",
    dimension: "Motivation",
    type: "Travaillomane",
    text: "Recevoir des retours détaillés m’encourage à progresser.",
  },
  {
    id: "q024",
    dimension: "Motivation",
    type: "Travaillomane",
    text: "Je préfère un environnement structuré à un climat trop informel.",
  },

  {
    id: "q025",
    dimension: "Force",
    type: "Travaillomane",
    text: "J'organise naturellement les tâches en étapes claires.",
  },
  {
    id: "q026",
    dimension: "Force",
    type: "Travaillomane",
    text: "Je suis à l'aise pour analyser des données complexes.",
  },
  {
    id: "q027",
    dimension: "Force",
    type: "Travaillomane",
    text: "On me fait confiance pour respecter les délais stricts.",
  },
  {
    id: "q028",
    dimension: "Force",
    type: "Travaillomane",
    text: "Je garde mon sang-froid lorsque les chiffres semblent impossibles.",
  },
  {
    id: "q029",
    dimension: "Force",
    type: "Travaillomane",
    text: "Je crée facilement des procédures pour améliorer l'efficacité.",
  },
  {
    id: "q030",
    dimension: "Force",
    type: "Travaillomane",
    text: "Je m'assure que rien n'a été oublié avant de déclarer un travail terminé.",
  },

  {
    id: "q031",
    dimension: "Stress",
    type: "Travaillomane",
    text: "Je relis plusieurs fois un e-mail avant de l’envoyer, de peur d’une erreur.",
  },
  {
    id: "q032",
    dimension: "Stress",
    type: "Travaillomane",
    text: "Je peux devenir impatient quand les autres improvisent.",
  },
  {
    id: "q033",
    dimension: "Stress",
    type: "Travaillomane",
    text: "Si un détail m'échappe, je continue d'y penser la nuit.",
  },
  {
    id: "q034",
    dimension: "Stress",
    type: "Travaillomane",
    text: "Je prends rarement de pauses jusqu'à ce que tout soit parfait.",
  },
  {
    id: "q035",
    dimension: "Stress",
    type: "Travaillomane",
    text: "Je corrige spontanément les documents des collègues.",
  },
  {
    id: "q036",
    dimension: "Stress",
    type: "Travaillomane",
    text: "Je me sens obligé de dire « oui » même si ma charge est déjà pleine.",
  },

  {
    id: "q037",
    dimension: "Motivation",
    type: "Persévérant",
    text: "Être reconnu pour mes convictions renforce mon engagement.",
  },
  {
    id: "q038",
    dimension: "Motivation",
    type: "Persévérant",
    text: "La cohérence entre paroles et actes des autres me motive.",
  },
  {
    id: "q039",
    dimension: "Motivation",
    type: "Persévérant",
    text: "J'aime quand on me consulte pour mon avis éclairé.",
  },
  {
    id: "q040",
    dimension: "Motivation",
    type: "Persévérant",
    text: "Être responsable d'un sujet me dynamise.",
  },
  {
    id: "q041",
    dimension: "Motivation",
    type: "Persévérant",
    text: "Je suis motivé par la quête d'exactitude.",
  },
  {
    id: "q042",
    dimension: "Motivation",
    type: "Persévérant",
    text: "Je préfère un débat fondé qu'une décision rapide.",
  },

  {
    id: "q043",
    dimension: "Force",
    type: "Persévérant",
    text: "Je détecte vite les incohérences dans un argumentaire.",
  },
  {
    id: "q044",
    dimension: "Force",
    type: "Persévérant",
    text: "Je suis loyal envers les causes qui me tiennent à cœur.",
  },
  {
    id: "q045",
    dimension: "Force",
    type: "Persévérant",
    text: "Je poursuis mes objectifs malgré les obstacles.",
  },
  {
    id: "q046",
    dimension: "Force",
    type: "Persévérant",
    text: "Je respecte rigoureusement mes principes.",
  },
  {
    id: "q047",
    dimension: "Force",
    type: "Persévérant",
    text: "On me considère comme fiable pour garder la mémoire des décisions.",
  },
  {
    id: "q048",
    dimension: "Force",
    type: "Persévérant",
    text: "Je défends volontiers ceux qui n'ont pas voix au chapitre.",
  },

  {
    id: "q049",
    dimension: "Stress",
    type: "Persévérant",
    text: "Je deviens pointilleux quand les autres manquent de précision.",
  },
  {
    id: "q050",
    dimension: "Stress",
    type: "Persévérant",
    text: "Je remarque immédiatement les écarts par rapport aux règles établies.",
  },
  {
    id: "q051",
    dimension: "Stress",
    type: "Persévérant",
    text: "Je peux insister longuement pour que justice soit faite.",
  },
  {
    id: "q052",
    dimension: "Stress",
    type: "Persévérant",
    text: "Je suis frustré quand mes conseils ne sont pas suivis.",
  },
  {
    id: "q053",
    dimension: "Stress",
    type: "Persévérant",
    text: "Je critique ouvertement ce qui me semble injuste.",
  },
  {
    id: "q054",
    dimension: "Stress",
    type: "Persévérant",
    text: "Je peux rester accroché à un sujet jusqu'à convaincre tout le monde.",
  },

  {
    id: "q055",
    dimension: "Motivation",
    type: "Promoteur",
    text: "Les défis à haute adrénaline me motivent.",
  },
  {
    id: "q056",
    dimension: "Motivation",
    type: "Promoteur",
    text: "Je suis stimulé par la possibilité de gagner vite.",
  },
  {
    id: "q057",
    dimension: "Motivation",
    type: "Promoteur",
    text: "J'aime les environnements où les règles sont flexibles.",
  },
  {
    id: "q058",
    dimension: "Motivation",
    type: "Promoteur",
    text: "La compétition amicale me donne de l'énergie.",
  },
  {
    id: "q059",
    dimension: "Motivation",
    type: "Promoteur",
    text: "Je cherche des projets où je peux négocier et influencer.",
  },
  {
    id: "q060",
    dimension: "Motivation",
    type: "Promoteur",
    text: "Une récompense tangible me motive plus que des compliments.",
  },

  {
    id: "q061",
    dimension: "Force",
    type: "Promoteur",
    text: "Je prends des décisions rapides avec peu d'informations.",
  },
  {
    id: "q062",
    dimension: "Force",
    type: "Promoteur",
    text: "Je garde mon sang-froid dans une crise.",
  },
  {
    id: "q063",
    dimension: "Force",
    type: "Promoteur",
    text: "Je persuade facilement un client hésitant.",
  },
  {
    id: "q064",
    dimension: "Force",
    type: "Promoteur",
    text: "Je vois rapidement comment maximiser un avantage.",
  },
  {
    id: "q065",
    dimension: "Force",
    type: "Promoteur",
    text: "Je m'adapte quand les plans changent soudainement.",
  },
  {
    id: "q066",
    dimension: "Force",
    type: "Promoteur",
    text: "Je reste optimiste même quand les autres doutent.",
  },

  {
    id: "q067",
    dimension: "Stress",
    type: "Promoteur",
    text: "Je peux court-circuiter un processus que je trouve trop lent.",
  },
  {
    id: "q068",
    dimension: "Stress",
    type: "Promoteur",
    text: "Je dis ce que je pense, même si ça choque.",
  },
  {
    id: "q069",
    dimension: "Stress",
    type: "Promoteur",
    text: "Je prends des risques sans toujours mesurer les conséquences.",
  },
  {
    id: "q070",
    dimension: "Stress",
    type: "Promoteur",
    text: "Je peux tester les limites de l'autorité pour voir jusqu'où aller.",
  },
  {
    id: "q071",
    dimension: "Stress",
    type: "Promoteur",
    text: "Je cherche des raccourcis pour arriver en tête.",
  },
  {
    id: "q072",
    dimension: "Stress",
    type: "Promoteur",
    text: "Je me lasse vite quand les discussions deviennent théoriques.",
  },

  {
    id: "q073",
    dimension: "Motivation",
    type: "Rebelle",
    text: "Je suis motivé quand le travail est ludique.",
  },
  {
    id: "q074",
    dimension: "Motivation",
    type: "Rebelle",
    text: "Un environnement coloré et vivant me stimule.",
  },
  {
    id: "q075",
    dimension: "Motivation",
    type: "Rebelle",
    text: "Je préfère un échange spontané à un long rapport.",
  },
  {
    id: "q076",
    dimension: "Motivation",
    type: "Rebelle",
    text: "Les surprises agréables nourrissent mon énergie.",
  },
  {
    id: "q077",
    dimension: "Motivation",
    type: "Rebelle",
    text: "Je trouve de l'inspiration dans une ambiance décontractée.",
  },
  {
    id: "q078",
    dimension: "Motivation",
    type: "Rebelle",
    text: "Je me lance volontiers dans une activité si elle paraît fun.",
  },

  {
    id: "q079",
    dimension: "Force",
    type: "Rebelle",
    text: "Je crée des slogans accrocheurs sans effort.",
  },
  {
    id: "q080",
    dimension: "Force",
    type: "Rebelle",
    text: "Je fais rire l'équipe pour relâcher la pression.",
  },
  {
    id: "q081",
    dimension: "Force",
    type: "Rebelle",
    text: "Je trouve des angles créatifs que personne n'avait vus.",
  },
  {
    id: "q082",
    dimension: "Force",
    type: "Rebelle",
    text: "Je capte l'attention grâce à mon expressivité.",
  },
  {
    id: "q083",
    dimension: "Force",
    type: "Rebelle",
    text: "Je relie des idées disparates en une vision originale.",
  },
  {
    id: "q084",
    dimension: "Force",
    type: "Rebelle",
    text: "Je remotive l'équipe quand l'ennui s'installe.",
  },

  {
    id: "q085",
    dimension: "Stress",
    type: "Rebelle",
    text: "Je boude quand on me donne des ordres secs.",
  },
  {
    id: "q086",
    dimension: "Stress",
    type: "Rebelle",
    text: "Je taquine pour masquer mon agacement.",
  },
  {
    id: "q087",
    dimension: "Stress",
    type: "Rebelle",
    text: "Je remets les tâches en dernier si elles manquent d'intérêt.",
  },
  {
    id: "q088",
    dimension: "Stress",
    type: "Rebelle",
    text: "Je peux dire « c'est nul » sans proposer de solution.",
  },
  {
    id: "q089",
    dimension: "Stress",
    type: "Rebelle",
    text: "Je cherche des distractions quand la routine me pèse.",
  },
  {
    id: "q090",
    dimension: "Stress",
    type: "Rebelle",
    text: "Je me sens incompris si l'atmosphère est trop formelle.",
  },

  {
    id: "q091",
    dimension: "Motivation",
    type: "Rêveur",
    text: "Je suis motivé lorsque j'ai du temps seul pour réfléchir.",
  },
  {
    id: "q092",
    dimension: "Motivation",
    type: "Rêveur",
    text: "Une consigne claire me permet de me mettre en action.",
  },
  {
    id: "q093",
    dimension: "Motivation",
    type: "Rêveur",
    text: "Je préfère un rythme calme pour donner le meilleur de moi-même.",
  },
  {
    id: "q094",
    dimension: "Motivation",
    type: "Rêveur",
    text: "La possibilité d'imaginer de nouveaux concepts m'inspire.",
  },
  {
    id: "q095",
    dimension: "Motivation",
    type: "Rêveur",
    text: "Je me sens en sécurité quand on me laisse observer avant d'agir.",
  },
  {
    id: "q096",
    dimension: "Motivation",
    type: "Rêveur",
    text: "J'apprécie que l'on respecte mon espace personnel.",
  },

  {
    id: "q097",
    dimension: "Force",
    type: "Rêveur",
    text: "Je reste calme même si tout le monde panique.",
  },
  {
    id: "q098",
    dimension: "Force",
    type: "Rêveur",
    text: "Je génère des idées originales pendant les moments de silence.",
  },
  {
    id: "q099",
    dimension: "Force",
    type: "Rêveur",
    text: "Je suis capable d'écouter longtemps sans interrompre.",
  },
  {
    id: "q100",
    dimension: "Force",
    type: "Rêveur",
    text: "Je conceptualise des systèmes complexes dans ma tête.",
  },
  {
    id: "q101",
    dimension: "Force",
    type: "Rêveur",
    text: "Je ne me laisse pas distraire par le bruit ambiant.",
  },
  {
    id: "q102",
    dimension: "Force",
    type: "Rêveur",
    text: "Je synthétise l'information pour proposer une vision globale.",
  },

  {
    id: "q103",
    dimension: "Stress",
    type: "Rêveur",
    text: "Je me déconnecte socialement, semblant « ailleurs ».",
  },
  {
    id: "q104",
    dimension: "Stress",
    type: "Rêveur",
    text: "Je remets à plus tard les décisions par crainte de me tromper.",
  },
  {
    id: "q105",
    dimension: "Stress",
    type: "Rêveur",
    text: "Je réponds par des phrases courtes pour éviter l'engagement.",
  },
  {
    id: "q106",
    dimension: "Stress",
    type: "Rêveur",
    text: "Je m'évade dans mes pensées lorsque la pression monte.",
  },
  {
    id: "q107",
    dimension: "Stress",
    type: "Rêveur",
    text: "Je laisse les autres prendre les devants si l'ambiance est tendue.",
  },
  {
    id: "q108",
    dimension: "Stress",
    type: "Rêveur",
    text: "Je deviens lent à réagir quand les demandes affluent.",
  },
];
