export const QUESTIONS = [
  {
    id: "q001",
    dimension: "Motivation",
    type: "Empathique",
    text: "Je recherche des contacts chaleureux pour me sentir en phase avec mon entourage.",
    en: "I seek warm connections to feel in tune with those around me.",
  },
  {
    id: "q002",
    dimension: "Motivation",
    type: "Empathique",
    text: "Être reconnu pour ma gentillesse me pousse à donner le meilleur de moi-même.",
    en: "Being recognized for my kindness motivates me to give my best.",
  },
  {
    id: "q003",
    dimension: "Motivation",
    type: "Empathique",
    text: "La convivialité d'une équipe est plus importante pour moi que la compétition.",
    en: "Team friendliness matters more to me than competition.",
  },
  {
    id: "q004",
    dimension: "Motivation",
    type: "Empathique",
    text: "Je me sens motivé quand on me remercie sincèrement pour mon soutien.",
    en: "I feel motivated when I am sincerely thanked for my support.",
  },
  {
    id: "q005",
    dimension: "Motivation",
    type: "Empathique",
    text: "Je suis prêt à aider sans réserve lorsque je me sens apprécié.",
    en: "I am ready to help without hesitation when I feel appreciated.",
  },
  {
    id: "q006",
    dimension: "Motivation",
    type: "Empathique",
    text: "Je choisis rarement un projet dépourvu d'humanité, même s'il est rentable.",
    en: "I rarely choose a project lacking humanity, even if it is profitable.",
  },

  {
    id: "q007",
    dimension: "Force",
    type: "Empathique",
    text: "J'arrive à comprendre l'humeur des autres sans qu'ils ne parlent.",
    en: "I can sense others' moods without them saying a word.",
  },
  {
    id: "q008",
    dimension: "Force",
    type: "Empathique",
    text: "Je crée naturellement une ambiance détendue et accueillante.",
    en: "I naturally create a relaxed and welcoming atmosphere.",
  },
  {
    id: "q009",
    dimension: "Force",
    type: "Empathique",
    text: "Je fais passer les besoins émotionnels de chacun avant les procédures.",
    en: "I put everyone's emotional needs before procedures.",
  },
  {
    id: "q010",
    dimension: "Force",
    type: "Empathique",
    text: "On me sollicite souvent pour calmer les tensions.",
    en: "I am often asked to ease tensions.",
  },
  {
    id: "q011",
    dimension: "Force",
    type: "Empathique",
    text: "Je perçois rapidement quand quelqu'un ne se sent pas inclus.",
    en: "I quickly notice when someone feels left out.",
  },
  {
    id: "q012",
    dimension: "Force",
    type: "Empathique",
    text: "Je sais exprimer de l'empathie même sous pression.",
    en: "I can express empathy even under pressure.",
  },

  {
    id: "q013",
    dimension: "Stress",
    type: "Empathique",
    text: "Une critique peut me troubler pendant des heures.",
    en: "A criticism can trouble me for hours.",
  },
  {
    id: "q014",
    dimension: "Stress",
    type: "Empathique",
    text: "Je minimise mes besoins pour éviter de déranger.",
    en: "I minimize my needs to avoid disturbing others.",
  },
  {
    id: "q015",
    dimension: "Stress",
    type: "Empathique",
    text: "Quand je me sens exclu, j'ai du mal à me concentrer.",
    en: "When I feel excluded, I have trouble concentrating.",
  },
  {
    id: "q016",
    dimension: "Stress",
    type: "Empathique",
    text: "Je peux accepter des tâches supplémentaires pour maintenir la paix.",
    en: "I can accept additional tasks to maintain peace.",
  },
  {
    id: "q017",
    dimension: "Stress",
    type: "Empathique",
    text: "Je prends immédiatement la responsabilité lorsqu'un conflit surgit.",
    en: "I immediately take responsibility when a conflict arises.",
  },
  {
    id: "q018",
    dimension: "Stress",
    type: "Empathique",
    text: "Je me sens coupable si quelqu'un est contrarié à cause de moi.",
    en: "I feel guilty if someone is upset because of me.",
  },

  {
    id: "q019",
    dimension: "Motivation",
    type: "Travaillomane",
    text: "Être reconnu pour la qualité de mon travail me stimule.",
    en: "Being recognized for the quality of my work stimulates me.",
  },
  {
    id: "q020",
    dimension: "Motivation",
    type: "Travaillomane",
    text: "Je suis motivé lorsqu'un projet a des objectifs mesurables.",
    en: "I am motivated when a project has measurable objectives.",
  },
  {
    id: "q021",
    dimension: "Motivation",
    type: "Travaillomane",
    text: "Un planning précis me donne de l'énergie.",
    en: "A precise schedule gives me energy.",
  },
  {
    id: "q022",
    dimension: "Motivation",
    type: "Travaillomane",
    text: "J'aime que mon expertise technique soit valorisée.",
    en: "I like my technical expertise to be valued.",
  },
  {
    id: "q023",
    dimension: "Motivation",
    type: "Travaillomane",
    text: "Recevoir des retours détaillés m'encourage à progresser.",
    en: "Receiving detailed feedback encourages me to progress.",
  },
  {
    id: "q024",
    dimension: "Motivation",
    type: "Travaillomane",
    text: "Je préfère un environnement structuré à un climat trop informel.",
    en: "I prefer a structured environment to an overly informal atmosphere.",
  },

  {
    id: "q025",
    dimension: "Force",
    type: "Travaillomane",
    text: "J'organise naturellement les tâches en étapes claires.",
    en: "I naturally organize tasks into clear steps.",
  },
  {
    id: "q026",
    dimension: "Force",
    type: "Travaillomane",
    text: "Je suis à l'aise pour analyser des données complexes.",
    en: "I am comfortable analyzing complex data.",
  },
  {
    id: "q027",
    dimension: "Force",
    type: "Travaillomane",
    text: "On me fait confiance pour respecter les délais stricts.",
    en: "I am trusted to meet strict deadlines.",
  },
  {
    id: "q028",
    dimension: "Force",
    type: "Travaillomane",
    text: "Je garde mon sang-froid lorsque les chiffres semblent impossibles.",
    en: "I keep my cool when the numbers seem impossible.",
  },
  {
    id: "q029",
    dimension: "Force",
    type: "Travaillomane",
    text: "Je crée facilement des procédures pour améliorer l'efficacité.",
    en: "I easily create procedures to improve efficiency.",
  },
  {
    id: "q030",
    dimension: "Force",
    type: "Travaillomane",
    text: "Je m'assure que rien n'a été oublié avant de déclarer un travail terminé.",
    en: "I make sure nothing has been forgotten before declaring work complete.",
  },

  {
    id: "q031",
    dimension: "Stress",
    type: "Travaillomane",
    text: "Je relis plusieurs fois un e-mail avant de l'envoyer, de peur d'une erreur.",
    en: "I read an email several times before sending it, fearing an error.",
  },
  {
    id: "q032",
    dimension: "Stress",
    type: "Travaillomane",
    text: "Je peux devenir impatient quand les autres improvisent.",
    en: "I can become impatient when others improvise.",
  },
  {
    id: "q033",
    dimension: "Stress",
    type: "Travaillomane",
    text: "Si un détail m'échappe, je continue d'y penser la nuit.",
    en: "If I miss a detail, I keep thinking about it at night.",
  },
  {
    id: "q034",
    dimension: "Stress",
    type: "Travaillomane",
    text: "Je prends rarement de pauses jusqu'à ce que tout soit parfait.",
    en: "I rarely take breaks until everything is perfect.",
  },
  {
    id: "q035",
    dimension: "Stress",
    type: "Travaillomane",
    text: "Je corrige spontanément les documents des collègues.",
    en: "I spontaneously correct colleagues' documents.",
  },
  {
    id: "q036",
    dimension: "Stress",
    type: "Travaillomane",
    text: "Je me sens obligé de dire « oui » même si ma charge est déjà pleine.",
    en: "I feel obligated to say 'yes' even if my workload is already full.",
  },

  {
    id: "q037",
    dimension: "Motivation",
    type: "Persévérant",
    text: "Être reconnu pour mes convictions renforce mon engagement.",
    en: "Being recognized for my convictions strengthens my commitment.",
  },
  {
    id: "q038",
    dimension: "Motivation",
    type: "Persévérant",
    text: "La cohérence entre paroles et actes des autres me motive.",
    en: "Consistency between others' words and actions motivates me.",
  },
  {
    id: "q039",
    dimension: "Motivation",
    type: "Persévérant",
    text: "J'aime quand on me consulte pour mon avis éclairé.",
    en: "I like being consulted for my informed opinion.",
  },
  {
    id: "q040",
    dimension: "Motivation",
    type: "Persévérant",
    text: "Être responsable d'un sujet me dynamise.",
    en: "Being responsible for a topic energizes me.",
  },
  {
    id: "q041",
    dimension: "Motivation",
    type: "Persévérant",
    text: "Je suis motivé par la quête d'exactitude.",
    en: "I am motivated by the pursuit of accuracy.",
  },
  {
    id: "q042",
    dimension: "Motivation",
    type: "Persévérant",
    text: "Je préfère un débat fondé qu'une décision rapide.",
    en: "I prefer a well-founded debate to a quick decision.",
  },

  {
    id: "q043",
    dimension: "Force",
    type: "Persévérant",
    text: "Je détecte vite les incohérences dans un argumentaire.",
    en: "I quickly detect inconsistencies in an argument.",
  },
  {
    id: "q044",
    dimension: "Force",
    type: "Persévérant",
    text: "Je suis loyal envers les causes qui me tiennent à cœur.",
    en: "I am loyal to causes close to my heart.",
  },
  {
    id: "q045",
    dimension: "Force",
    type: "Persévérant",
    text: "Je poursuis mes objectifs malgré les obstacles.",
    en: "I pursue my objectives despite obstacles.",
  },
  {
    id: "q046",
    dimension: "Force",
    type: "Persévérant",
    text: "Je respecte rigoureusement mes principes.",
    en: "I strictly adhere to my principles.",
  },
  {
    id: "q047",
    dimension: "Force",
    type: "Persévérant",
    text: "On me considère comme fiable pour garder la mémoire des décisions.",
    en: "I am considered reliable for keeping track of decisions.",
  },
  {
    id: "q048",
    dimension: "Force",
    type: "Persévérant",
    text: "Je défends volontiers ceux qui n'ont pas voix au chapitre.",
    en: "I willingly defend those who have no say.",
  },

  {
    id: "q049",
    dimension: "Stress",
    type: "Persévérant",
    text: "Je deviens pointilleux quand les autres manquent de précision.",
    en: "I become picky when others lack precision.",
  },
  {
    id: "q050",
    dimension: "Stress",
    type: "Persévérant",
    text: "Je remarque immédiatement les écarts par rapport aux règles établies.",
    en: "I immediately notice deviations from established rules.",
  },
  {
    id: "q051",
    dimension: "Stress",
    type: "Persévérant",
    text: "Je peux insister longuement pour que justice soit faite.",
    en: "I can insist at length for justice to be done.",
  },
  {
    id: "q052",
    dimension: "Stress",
    type: "Persévérant",
    text: "Je suis frustré quand mes conseils ne sont pas suivis.",
    en: "I am frustrated when my advice is not followed.",
  },
  {
    id: "q053",
    dimension: "Stress",
    type: "Persévérant",
    text: "Je critique ouvertement ce qui me semble injuste.",
    en: "I openly criticize what seems unfair to me.",
  },
  {
    id: "q054",
    dimension: "Stress",
    type: "Persévérant",
    text: "Je peux rester accroché à un sujet jusqu'à convaincre tout le monde.",
    en: "I can stay stuck on a topic until I convince everyone.",
  },

  {
    id: "q055",
    dimension: "Motivation",
    type: "Promoteur",
    text: "Les défis à haute adrénaline me motivent.",
    en: "High-adrenaline challenges motivate me.",
  },
  {
    id: "q056",
    dimension: "Motivation",
    type: "Promoteur",
    text: "Je suis stimulé par la possibilité de gagner vite.",
    en: "I am stimulated by the possibility of winning quickly.",
  },
  {
    id: "q057",
    dimension: "Motivation",
    type: "Promoteur",
    text: "J'aime les environnements où les règles sont flexibles.",
    en: "I like environments where rules are flexible.",
  },
  {
    id: "q058",
    dimension: "Motivation",
    type: "Promoteur",
    text: "La compétition amicale me donne de l'énergie.",
    en: "Friendly competition gives me energy.",
  },
  {
    id: "q059",
    dimension: "Motivation",
    type: "Promoteur",
    text: "Je cherche des projets où je peux négocier et influencer.",
    en: "I seek projects where I can negotiate and influence.",
  },
  {
    id: "q060",
    dimension: "Motivation",
    type: "Promoteur",
    text: "Une récompense tangible me motive plus que des compliments.",
    en: "A tangible reward motivates me more than compliments.",
  },

  {
    id: "q061",
    dimension: "Force",
    type: "Promoteur",
    text: "Je prends des décisions rapides avec peu d'informations.",
    en: "I make quick decisions with little information.",
  },
  {
    id: "q062",
    dimension: "Force",
    type: "Promoteur",
    text: "Je garde mon sang-froid dans une crise.",
    en: "I keep my cool in a crisis.",
  },
  {
    id: "q063",
    dimension: "Force",
    type: "Promoteur",
    text: "Je persuade facilement un client hésitant.",
    en: "I easily persuade a hesitant client.",
  },
  {
    id: "q064",
    dimension: "Force",
    type: "Promoteur",
    text: "Je vois rapidement comment maximiser un avantage.",
    en: "I quickly see how to maximize an advantage.",
  },
  {
    id: "q065",
    dimension: "Force",
    type: "Promoteur",
    text: "Je m'adapte quand les plans changent soudainement.",
    en: "I adapt when plans change suddenly.",
  },
  {
    id: "q066",
    dimension: "Force",
    type: "Promoteur",
    text: "Je reste optimiste même quand les autres doutent.",
    en: "I stay optimistic even when others doubt.",
  },

  {
    id: "q067",
    dimension: "Stress",
    type: "Promoteur",
    text: "Je peux court-circuiter un processus que je trouve trop lent.",
    en: "I can bypass a process I find too slow.",
  },
  {
    id: "q068",
    dimension: "Stress",
    type: "Promoteur",
    text: "Je dis ce que je pense, même si ça choque.",
    en: "I say what I think, even if it shocks.",
  },
  {
    id: "q069",
    dimension: "Stress",
    type: "Promoteur",
    text: "Je prends des risques sans toujours mesurer les conséquences.",
    en: "I take risks without always measuring the consequences.",
  },
  {
    id: "q070",
    dimension: "Stress",
    type: "Promoteur",
    text: "Je peux tester les limites de l'autorité pour voir jusqu'où aller.",
    en: "I can test the limits of authority to see how far I can go.",
  },
  {
    id: "q071",
    dimension: "Stress",
    type: "Promoteur",
    text: "Je cherche des raccourcis pour arriver en tête.",
    en: "I look for shortcuts to get ahead.",
  },
  {
    id: "q072",
    dimension: "Stress",
    type: "Promoteur",
    text: "Je me lasse vite quand les discussions deviennent théoriques.",
    en: "I quickly get bored when discussions become theoretical.",
  },

  {
    id: "q073",
    dimension: "Motivation",
    type: "Rebelle",
    text: "Je suis motivé quand le travail est ludique.",
    en: "I am motivated when work is playful.",
  },
  {
    id: "q074",
    dimension: "Motivation",
    type: "Rebelle",
    text: "Un environnement coloré et vivant me stimule.",
    en: "A colorful and lively environment stimulates me.",
  },
  {
    id: "q075",
    dimension: "Motivation",
    type: "Rebelle",
    text: "Je préfère un échange spontané à un long rapport.",
    en: "I prefer spontaneous exchange to a long report.",
  },
  {
    id: "q076",
    dimension: "Motivation",
    type: "Rebelle",
    text: "Les surprises agréables nourrissent mon énergie.",
    en: "Pleasant surprises feed my energy.",
  },
  {
    id: "q077",
    dimension: "Motivation",
    type: "Rebelle",
    text: "Je trouve de l'inspiration dans une ambiance décontractée.",
    en: "I find inspiration in a relaxed atmosphere.",
  },
  {
    id: "q078",
    dimension: "Motivation",
    type: "Rebelle",
    text: "Je me lance volontiers dans une activité si elle paraît fun.",
    en: "I readily engage in an activity if it seems fun.",
  },

  {
    id: "q079",
    dimension: "Force",
    type: "Rebelle",
    text: "Je crée des slogans accrocheurs sans effort.",
    en: "I create catchy slogans effortlessly.",
  },
  {
    id: "q080",
    dimension: "Force",
    type: "Rebelle",
    text: "Je fais rire l'équipe pour relâcher la pression.",
    en: "I make the team laugh to release pressure.",
  },
  {
    id: "q081",
    dimension: "Force",
    type: "Rebelle",
    text: "Je trouve des angles créatifs que personne n'avait vus.",
    en: "I find creative angles that no one had seen.",
  },
  {
    id: "q082",
    dimension: "Force",
    type: "Rebelle",
    text: "Je capte l'attention grâce à mon expressivité.",
    en: "I capture attention through my expressiveness.",
  },
  {
    id: "q083",
    dimension: "Force",
    type: "Rebelle",
    text: "Je relie des idées disparates en une vision originale.",
    en: "I connect disparate ideas into an original vision.",
  },
  {
    id: "q084",
    dimension: "Force",
    type: "Rebelle",
    text: "Je remotive l'équipe quand l'ennui s'installe.",
    en: "I remotivate the team when boredom sets in.",
  },

  {
    id: "q085",
    dimension: "Stress",
    type: "Rebelle",
    text: "Je boude quand on me donne des ordres secs.",
    en: "I sulk when given blunt orders.",
  },
  {
    id: "q086",
    dimension: "Stress",
    type: "Rebelle",
    text: "Je taquine pour masquer mon agacement.",
    en: "I tease to mask my annoyance.",
  },
  {
    id: "q087",
    dimension: "Stress",
    type: "Rebelle",
    text: "Je remets les tâches en dernier si elles manquent d'intérêt.",
    en: "I put off tasks if they lack interest.",
  },
  {
    id: "q088",
    dimension: "Stress",
    type: "Rebelle",
    text: "Je peux dire « c'est nul » sans proposer de solution.",
    en: "I can say 'this sucks' without offering a solution.",
  },
  {
    id: "q089",
    dimension: "Stress",
    type: "Rebelle",
    text: "Je cherche des distractions quand la routine me pèse.",
    en: "I seek distractions when routine weighs on me.",
  },
  {
    id: "q090",
    dimension: "Stress",
    type: "Rebelle",
    text: "Je me sens incompris si l'atmosphère est trop formelle.",
    en: "I feel misunderstood if the atmosphere is too formal.",
  },

  {
    id: "q091",
    dimension: "Motivation",
    type: "Rêveur",
    text: "Je suis motivé lorsque j'ai du temps seul pour réfléchir.",
    en: "I am motivated when I have time alone to think.",
  },
  {
    id: "q092",
    dimension: "Motivation",
    type: "Rêveur",
    text: "Une consigne claire me permet de me mettre en action.",
    en: "A clear instruction allows me to take action.",
  },
  {
    id: "q093",
    dimension: "Motivation",
    type: "Rêveur",
    text: "Je préfère un rythme calme pour donner le meilleur de moi-même.",
    en: "I prefer a calm pace to give my best.",
  },
  {
    id: "q094",
    dimension: "Motivation",
    type: "Rêveur",
    text: "La possibilité d'imaginer de nouveaux concepts m'inspire.",
    en: "The possibility of imagining new concepts inspires me.",
  },
  {
    id: "q095",
    dimension: "Motivation",
    type: "Rêveur",
    text: "Je me sens en sécurité quand on me laisse observer avant d'agir.",
    en: "I feel secure when allowed to observe before acting.",
  },
  {
    id: "q096",
    dimension: "Motivation",
    type: "Rêveur",
    text: "J'apprécie que l'on respecte mon espace personnel.",
    en: "I appreciate when my personal space is respected.",
  },

  {
    id: "q097",
    dimension: "Force",
    type: "Rêveur",
    text: "Je reste calme même si tout le monde panique.",
    en: "I stay calm even when everyone panics.",
  },
  {
    id: "q098",
    dimension: "Force",
    type: "Rêveur",
    text: "Je génère des idées originales pendant les moments de silence.",
    en: "I generate original ideas during moments of silence.",
  },
  {
    id: "q099",
    dimension: "Force",
    type: "Rêveur",
    text: "Je suis capable d'écouter longtemps sans interrompre.",
    en: "I can listen for a long time without interrupting.",
  },
  {
    id: "q100",
    dimension: "Force",
    type: "Rêveur",
    text: "Je conceptualise des systèmes complexes dans ma tête.",
    en: "I conceptualize complex systems in my head.",
  },
  {
    id: "q101",
    dimension: "Force",
    type: "Rêveur",
    text: "Je ne me laisse pas distraire par le bruit ambiant.",
    en: "I don't let ambient noise distract me.",
  },
  {
    id: "q102",
    dimension: "Force",
    type: "Rêveur",
    text: "Je synthétise l'information pour proposer une vision globale.",
    en: "I synthesize information to propose a global vision.",
  },

  {
    id: "q103",
    dimension: "Stress",
    type: "Rêveur",
    text: "Je me déconnecte socialement, semblant « ailleurs ».",
    en: "I disconnect socially, seeming 'elsewhere'.",
  },
  {
    id: "q104",
    dimension: "Stress",
    type: "Rêveur",
    text: "Je remets à plus tard les décisions par crainte de me tromper.",
    en: "I postpone decisions for fear of making mistakes.",
  },
  {
    id: "q105",
    dimension: "Stress",
    type: "Rêveur",
    text: "Je réponds par des phrases courtes pour éviter l'engagement.",
    en: "I answer with short phrases to avoid commitment.",
  },
  {
    id: "q106",
    dimension: "Stress",
    type: "Rêveur",
    text: "Je m'évade dans mes pensées lorsque la pression monte.",
    en: "I escape into my thoughts when pressure rises.",
  },
  {
    id: "q107",
    dimension: "Stress",
    type: "Rêveur",
    text: "Je laisse les autres prendre les devants si l'ambiance est tendue.",
    en: "I let others take the lead if the atmosphere is tense.",
  },
  {
    id: "q108",
    dimension: "Stress",
    type: "Rêveur",
    text: "Je deviens lent à réagir quand les demandes affluent.",
    en: "I become slow to react when demands pile up.",
  },
];
